# Generated by Django 3.0.6 on 2020-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.CharField(choices=[('ISLAMABAD', 'Islamabad'), ('LAHORE', 'Lahore'), ('KARACHI', 'Karachi'), ('SIALOT', 'Sialkot'), ('RAWALPINDI', 'Rawalpindi'), ('HYDERABAD', 'Hyderabad')], max_length=12),
        ),
    ]
